import Navbar from "@/components/navigation/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/navigation/Footer";
import Sidebar from "@/components/navigation/Sidebar";
import { NavigationContextProvider } from "@/contexts/navigaionContext";
import SearchModal from "@/components/modals/SearchModal";
import { UserContextProvider } from "@/contexts/userContext";
import { CartContextProvider } from "@/contexts/cartContext";
import CartModal from "@/components/modals/CartModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "De Kreator Idea",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative">
        <UserContextProvider>
          <NavigationContextProvider>
            <CartContextProvider>
              <Sidebar />
              <Navbar />
              <SearchModal />
              <CartModal />
              {children}
              <Footer />
            </CartContextProvider>
          </NavigationContextProvider>
        </UserContextProvider>
      </body>
    </html>
  );
}
